version: '2'

services:
  debugger-source:
    build: ./debugger

  app:
    build: ./app
    volumes_from:
      - debugger-source
    ports:
      - 8080:8080  # debugger port
      - 8090:8090  # application port
